# Generated by Django 3.1.3 on 2023-12-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=12)),
                ('Subtitulo', models.CharField(max_length=12)),
                ('FechaPublicacion', models.DateField()),
                ('Editor', models.CharField(max_length=12)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Imagen', models.CharField(max_length=50)),
                ('autor', models.IntegerField()),
                ('categoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=15)),
                ('Libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.libro')),
            ],
        ),
        migrations.CreateModel(
            name='autores',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=15)),
                ('Libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busqueda.libro')),
            ],
        ),
    ]
