# Generated by Django 3.1.3 on 2023-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_auto_20231219_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
    ]
