# Generated by Django 3.1.3 on 2023-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_auto_20231220_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='FechaPublicacion',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Titulo',
            field=models.CharField(max_length=50),
        ),
    ]
